//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `scheduler_control_root.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cecdat.schedule.control.rpc;

public class RpcException extends com.zeroc.Ice.UserException
{
    public RpcException()
    {
        this.code = "";
        this.message = "";
    }

    public RpcException(Throwable cause)
    {
        super(cause);
        this.code = "";
        this.message = "";
    }

    public RpcException(String code, String message)
    {
        this.code = code;
        this.message = message;
    }

    public RpcException(String code, String message, Throwable cause)
    {
        super(cause);
        this.code = code;
        this.message = message;
    }

    public String ice_id()
    {
        return "::rpc::RpcException";
    }

    public String code;

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::rpc::RpcException", -1, true);
        ostr_.writeString(code);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        code = istr_.readString();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 2704350745482835770L;
}
