//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `scheduler_control_airflow.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cecdat.schedule.control.rpc.bean;

/** @hidden */
public class _AirflowControlServicePrxI extends com.zeroc.Ice._ObjectPrxI implements AirflowControlServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
