//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `scheduler_control_airflow.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cecdat.schedule.control.rpc.bean;

public interface AirflowControlService extends com.zeroc.Ice.Object
{
    void taskFailureCallback(TaskFailureReq req, com.zeroc.Ice.Current current)
        throws com.cecdat.schedule.control.rpc.RpcException;

    void taskSuccessCallback(TaskSuccessReq req, com.zeroc.Ice.Current current)
        throws com.cecdat.schedule.control.rpc.RpcException;

    void taskExecuteCallback(TaskExecuteReq req, com.zeroc.Ice.Current current)
        throws com.cecdat.schedule.control.rpc.RpcException;

    void dagFailureCallback(DagFailureReq req, com.zeroc.Ice.Current current)
        throws com.cecdat.schedule.control.rpc.RpcException;

    void dagSuccessCallback(DagSuccessReq req, com.zeroc.Ice.Current current)
        throws com.cecdat.schedule.control.rpc.RpcException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::rpc::bean::AirflowControlService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::rpc::bean::AirflowControlService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_taskFailureCallback(AirflowControlService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        TaskFailureReq iceP_req;
        iceP_req = TaskFailureReq.ice_read(istr);
        inS.endReadParams();
        obj.taskFailureCallback(iceP_req, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_taskSuccessCallback(AirflowControlService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        TaskSuccessReq iceP_req;
        iceP_req = TaskSuccessReq.ice_read(istr);
        inS.endReadParams();
        obj.taskSuccessCallback(iceP_req, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_taskExecuteCallback(AirflowControlService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        TaskExecuteReq iceP_req;
        iceP_req = TaskExecuteReq.ice_read(istr);
        inS.endReadParams();
        obj.taskExecuteCallback(iceP_req, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_dagFailureCallback(AirflowControlService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        DagFailureReq iceP_req;
        iceP_req = DagFailureReq.ice_read(istr);
        inS.endReadParams();
        obj.dagFailureCallback(iceP_req, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_dagSuccessCallback(AirflowControlService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        DagSuccessReq iceP_req;
        iceP_req = DagSuccessReq.ice_read(istr);
        inS.endReadParams();
        obj.dagSuccessCallback(iceP_req, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "dagFailureCallback",
        "dagSuccessCallback",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "taskExecuteCallback",
        "taskFailureCallback",
        "taskSuccessCallback"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_dagFailureCallback(this, in, current);
            }
            case 1:
            {
                return _iceD_dagSuccessCallback(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_taskExecuteCallback(this, in, current);
            }
            case 7:
            {
                return _iceD_taskFailureCallback(this, in, current);
            }
            case 8:
            {
                return _iceD_taskSuccessCallback(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
