//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `scheduler_control_airflow.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.cecdat.schedule.control.rpc.bean;

public class TaskExecuteReq implements java.lang.Cloneable,
                                       java.io.Serializable
{
    public String taskId;

    public String getTaskId()
    {
        return taskId;
    }

    public void setTaskId(String taskId)
    {
        this.taskId = taskId;
    }

    public TaskExecuteReq()
    {
        this.taskId = "";
    }

    public TaskExecuteReq(String taskId)
    {
        this.taskId = taskId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        TaskExecuteReq r = null;
        if(rhs instanceof TaskExecuteReq)
        {
            r = (TaskExecuteReq)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::rpc::bean::TaskExecuteReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        return h_;
    }

    public TaskExecuteReq clone()
    {
        TaskExecuteReq c = null;
        try
        {
            c = (TaskExecuteReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.taskId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, TaskExecuteReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public TaskExecuteReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        TaskExecuteReq v = new TaskExecuteReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<TaskExecuteReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, TaskExecuteReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<TaskExecuteReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(TaskExecuteReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final TaskExecuteReq _nullMarshalValue = new TaskExecuteReq();

    /** @hidden */
    public static final long serialVersionUID = 8319061469791473873L;
}
